title: Aris Antoniadis
url: "https://arisantoniadis.com"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://www.youtube.com/watch?v=pUyrgEtzbvM"
footer_text: "By Aris Antoniadis"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Photos"
   link: "{{ site.baseurl }}/photos/"
 - name: "Blog"
   link: "https://www.frontalfoundations.com/blog"
